data:
  base_dir: /scratch/gpfs/IOJALVO/gnn-tracking/object_condensation/codalab-data
  batch_size: 32
  data_dir: /scratch/gpfs/IOJALVO/gnn-tracking/object_condensation/codalab-data/part_1
  event_processor:
    n_neighbors: 20
  include_all_parts: true
  num_workers: 0
  parts_glob: part_*
  random_seed: 42
  test_split: 0.1
  val_split: 0.2
environment:
  hit_filters: {}
  particle_filters:
    nhits_max: 20
    nhits_min: 4
    pt: 0.5
  proximity_threshold: 50.0
  use_distance_reward: false
  use_truth_path_plan: true
model:
  batch_size: 32
  episode_length: 200
  eps_end: 0.01
  eps_last_frame: 5000
  eps_start: 1.0
  gamma: 0.99
  lr: 0.0005
  num_agents: 10
  replay_size: 10000
  sync_rate: 10
  warm_start_size: 1000
  warm_start_steps: 2000
trainer:
  accelerator: gpu
  callbacks:
    checkpoint:
      filename: best-{epoch:02d}-{val_hit_accuracy:.4f}
      mode: max
      monitor: val_hit_accuracy
      save_last: true
      save_top_k: 1
    early_stopping:
      check_val_every_n_epoch: 1
      min_delta: 0.001
      mode: max
      monitor: val_hit_accuracy
      patience: 50
  devices: 1
  gradient_clip_val: 10.0
  log_every_n_steps: 10
  max_epochs: 5000
wandb:
  log_model: true
  name: multiagent_initial_run
  project: RLTracking
